name: Asana task
description: Start working on an Asana task
title: <replace with Asana task title>
labels: ["bug", "triage"]
body:
  - type: input
    id: asana-link
    attributes:
      label: Asana task link
      description: Copy from Asana task page
      placeholder: |
        Ex. https://app.asana.com/...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Add some descriptions...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
          - OS:
          - Node:
          - npm:
      render: markdown
    validations:
      required: false
