name: Bug Report From Asana
description: Start working on an Asana task
title: Replace with Asana task title
labels: ["bug", "triage"]
assignees:
body:
  - type: input
    id: asana-link
    attributes:
      label: Asana task link
      description: Copy from Asana task page
      placeholder: |
      ex. https://app.asana.com/...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
