name: Asana task
description: Start working on an Asana task
title: <replace with Asana task title>
labels: ["bug", "triage"]
body:
  - type: input
    id: asana-link
    attributes:
      label: Asana task link
      description: Copy from Asana task page
      placeholder: |
        Ex. https://app.asana.com/...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Add some descriptions...
    validations:
      required: false
